version: '3'

services:
  redis:
    container_name: "my-redis-container"
    image: "redis:7.2.3-bookworm"
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"
    # append-only: write into disk
    #command: redis-server --appendonly yes
