container.dev:
	docker compose -f docker-compose.yaml up

connect:
	go run cmd/connect/connect.go

set:
	go run cmd/set/set.go

get:
	go run cmd/get/get.go

update:
	go run cmd/update/update.go

delete:
	go run cmd/delete/delete.go

demo:
	go run cmd/demo/demo.go